apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my_app
spec:
  replicas: 2
  selector:
    matchLabels:
      my_label: container-fastapi
  template:
    metadata: 
      labels: 
        my_label: container-fastapi
    spec:
      containers:
      - name: fastapi
        image: datascientest/fastapi:1.0.0